name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Validate Release Type Selection
        id: validate_release_type
        run: |
          DESCRIPTION="${{ github.event.pull_request.body }}"
          # Count the number of [x] in DESCRIPTION
          count=$(echo "$DESCRIPTION" | grep -o '\[x\]' | wc -l)
          
          # Check if count is more than 1
          if [ "$count" -gt 1 ]; then
            echo "Error: More than one option is selected."
            exit 1
          else
            echo "Only one option is selected."
            exit 0
          fi
          echo "Major Count: $count"
