name: Java CI with Maven

on: pull_request

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
     
      - name: Validate PR Template
        id: validate
        run: |
          # Your validation logic here
          # Example: Setting a variable MY_VAR
          echo "MY_VAR=value_from_validation" >> $GITHUB_ENV

      - name: Save variable as artifact
        run: |
          echo "MY_VAR=$MY_VAR" > my_var.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-var-artifact
          path: my_var.txt
