name: PR Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate PR Template
        id: validate
        run: |
          # Your validation logic here
          # Example: Setting a variable MY_VAR
          echo "MY_VAR=value_from_validation" >> $GITHUB_ENV

      - name: Save variable as artifact
        run: |
          echo "MY_VAR=$MY_VAR" > my_var.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-var-artifact
          path: my_var.txt
