name: Java CI with Maven

on: pull_request

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Validate Release Type Selection
        id: validate_release_type
        run: |
          DESCRIPTION="${{ github.event.pull_request.body }}"
          # Extract the selected option
          selected_option=$(echo "$DESCRIPTION" | grep -oP '(?<=\[x\] ).*')
          
          # Count the number of [x] in DESCRIPTION
          count=$(echo "$DESCRIPTION" | grep -o '\[x\]' | wc -l)
          
          # Check if at least one option is selected
          if [ "$count" -lt 1 ]; then
            echo "Error: No option is selected."
            exit 1
          elif [ "$count" -gt 1 ]; then
            echo "Error: More than one option is selected."
            exit 1
          else
            echo "Selected option: $selected_option"
            echo "release_type=$selected_option" > release_type.txt
            exit 0
          fi
          ls -R
      - name: Save variable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-artifact
          path: release_type.txt
          retention-days: 90
