name: Add Temporary File to PR Branch

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  add-temp-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Create Temporary File
        run: echo "Temporary file content" > temp-file.txt

      - name: Commit and Push Temporary File
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add temp-file.txt
          git commit -m "Add temporary file"
          git push origin HEAD:${{ github.head_ref }}
