name: Remove Temporary File on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  remove-temp-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4

      - name: Remove Temporary File
        run: |
          if [ -f temp-file.txt ]; then
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git rm temp-file.txt
            git commit -m "Remove temporary file"
            git push origin main
          else
            echo "Temporary file not found, nothing to remove."
          fi
