name: Push to Main

on:
  push:
    branches:
      - main

jobs:
  use-var:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-var-artifact
          path: .

      - name: Read variable from artifact
        id: read-var
        run: |
          MY_VAR=$(cat my_var.txt)
          echo "MY_VAR=$MY_VAR" >> $GITHUB_ENV

      - name: Use the variable
        run: |
          echo "The value of MY_VAR is $MY_VAR"
